import type { Metadata } from "next";
import { Poppins} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Provider from "@/components/Provider";
import ScrollToTop from "@/components/ScrollToTop";

const font = Poppins({
  weight:['100','200','300','400','500','600','700','800','900'],
  subsets:['latin'],  
})

export const metadata: Metadata = {
  title: "E-Book",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      >
        <Provider>
        <Navbar/>
        {children}
        <Footer/>
        <ScrollToTop/>
        </Provider>
      </body>
    </html>
  );
}
